# This file is used by the Thunderstore CLI to build and publish your mod to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "ResoniteModding"
name = "BepInExResoniteShim" # Change this to your mod's name, no spaces or special characters, max 128 characters
versionNumber = "0.8.2" # Change this to your mod's version, must be in semantic versioning format (e.g. 1.0.0, 2.1.3, 0.1.0-alpha.1)
description = "Patches which allow the game to run with BepInEx loaded"
websiteUrl = "https://github.com/ResoniteModding/BepInExResoniteShim"
containsNsfwContent = false

# List any dependencies your mod has here, in the format "namespace-modname" = "version-constraint"
[package.dependencies]

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

# Copy the compiled DLL to the plugins folder in the mod package
[[build.copy]]
source = "./bin/Release/BepInExResoniteShim.dll"
target = "plugins/BepInExResoniteShim/"

# Include the PDB file for better debugging support
# [[build.copy]]
# source = "./bin/Release/BepInExResoniteShim.pdb"
# target = "plugins/BepInExResoniteShim/"

# Uncomment the following lines to include CHANGELOG file in your mod package. https://wiki.thunderstore.io/mods/updating-a-package#changelog
# [[build.copy]]
# source = "./CHANGELOG.md"
# target = "/"

# Uncomment the following line to include LICENSE file in your mod package, if you have one.
[[build.copy]]
source = "./LICENSE"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [ "libraries" ] # TODO: Change this to your mod's categories, see https://thunderstore.io/api/experimental/community/resonite/category/ for a list of available categories